### PR TITLE
README added for year-stat.py

### PR DESCRIPTION
**Pull request by iCHAIT**

### CODE REVIEW

**Comment by dufferzafar** [comment]
Make this a part of your other pull. #5

**Comment by iCHAIT** [comment]
How am I suppose to do that ?
The PR #5  is on a different branch and this one is on another.

If you could throw some light?

**Comment by dufferzafar** [comment]
Well, add this file to the same branch as #5, commit and push!

**Comment by iCHAIT** [comment]
This file is already present on the branch `doc`.
What about that?
I thought we would just update that particular README as we add the scripts

**Comment by dufferzafar** [comment]
Just cherry-pick this commit onto that branch.

`git checkout doc`

`git cherry-pick 8ffcbe8`

`git push`

**Pull request closed without merging**
